### ISSUE TITLE
安装cli报错

### ISSUE THREAD

**Issue by kuange** [heyui/heyui#16]
```
npm WARN sass-loader@6.0.7 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shen/.npm/_logs/2018-08-07T03_13_28_356Z-debug.log
````

**Comment by Puuuudding** [comment]
请问你是如何操作的？`npm -g i hey-cli`么？

**Comment by kuange** [comment]
@Puuuudding 是的呀

**Comment by kuange** [comment]
node v8.11.3
npm 5.6.0

**Comment by kuange** [comment]
@Puuuudding 
npm 升级到6.3 也一样的问题

**Comment by Puuuudding** [comment]
pngquant在npm install时会执行额外的安装脚本，内容比较大，你需要检查一下自己的网络确保安装成功，多次都不行的话尝试使用cnpm来安装

**Comment by kuange** [comment]
@Puuuudding shadowsocks 没关过的...

**Comment by kuange** [comment]
```
> pngquant-bin@4.0.0 postinstall /usr/local/lib/node_modules/hey-cli/node_modules/pngquant-bin
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/usr/local/lib/node_modules/hey-cli/node_modules/pngquant-bin/vendor'
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
/usr/local/lib/node_modules/hey-cli/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/usr/local/lib/node_modules/hey-cli/node_modules/onetime/index.js:15:11)
    at /usr/local/lib/node_modules/hey-cli/node_modules/bin-wrapper/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/hey-cli/node_modules/concat-stream/index.js:37:43)
    at emitNone (events.js:111:20)
    at ConcatStream.emit (events.js:208:7)
    at finishMaybe (/usr/local/lib/node_modules/hey-cli/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/usr/local/lib/node_modules/hey-cli/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/hey-cli/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/hey-cli/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:313:30)
npm WARN sass-loader@6.0.7 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shen/.npm/_logs/2018-08-08T01_39_12_235Z-debug.log
```
@Puuuudding

**Comment by kuange** [comment]
必须用 
```
# 新版本 npm
sudo npm install -g hey-cli --unsafe-perm=true --allow-root
```
